name: Build, Compose, Cleanup
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - shell: bash
        name: Build image lalu push ke registry
        env:
          dotenv: ${{ secrets.ENV }}
          username: ${{ secrets.USERNAME }}
          docker_password: ${{ secrets.PASSWORD }}
        run: |
          echo "$dotenv" > .env
          docker login -u "$username" -p "$password"
          docker build -t devopsofthemoon/campushub .
          docker push devopsofthemoon/campushub

  compose:
    needs: build
    runs-on: self-hosted
    steps:
      - shell: bash
        name: Compose up
        run: docker-compose -f /campushub/docker-compose.yml up -d