name: Build, Compose, Cleanup
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build image lalu push ke registry
        run: |
          echo "${{ secrets.ENV }}" > .env
          docker build -t devopsofthemoon/campushub .
          docker push devopsofthemoon/campushub
