on:
  push:
    branches:
    - main

jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
    - run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        docker build -t devopsofthemoon/campushub .
        docker push devopsofthemoon/campushub
