name: Build, Compose, Cleanup
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build image lalu push ke registry
        env:
          dotenv: ${{ secrets.env }}
          username: ${{ secrets.username }}
          docker_password: ${{ secrets.password }}
        run: |
          echo "$dotenv" > .env
          docker login -u $username -p $password
          docker build -t devopsofthemoon/campushub .
          docker push devopsofthemoon/campushub