name: Build, Compose, Cleanup
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - shell: bash
        name: Build image lalu push ke registry
        env:
          dotenv: ${{ secrets.env }}
          username: ${{ secrets.username }}
          docker_password: ${{ secrets.password }}
        run: |
          echo "$dotenv" > .env
          docker login -u "$username" -p "$password"
          docker build -t devopsofthemoon/campushub .
          docker push devopsofthemoon/campushub

  compose:
    needs: build
    runs-on: self-hosted
    steps:
      - shell: bash
        name: Compose up
        run: docker-compose -f /campushub/docker-compose.yml up -d

  cleanup:
    needs: compose
    runs-on: self-hosted
    steps:
      - shell: bash
        name: Cleanup everything
        run: |
          docker builder prune -af
          docker system prune -af
          rm -rf /home/actions-runner/_work