name: Build, Compose, Cleanup
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Build image lalu push ke registry
        run: |
          ls -al
          echo "${{ secrets.ENV }}" > .env
          docker build -t devopsofthemoon/campushub .
          docker push devopsofthemoon/campushub
